/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as IceyCrewRouteImport } from './routes/icey-crew'
import { Route as FindTruckRouteImport } from './routes/find-truck'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IceyCrewRoute = IceyCrewRouteImport.update({
  id: '/icey-crew',
  path: '/icey-crew',
  getParentRoute: () => rootRouteImport,
} as any)
const FindTruckRoute = FindTruckRouteImport.update({
  id: '/find-truck',
  path: '/find-truck',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find-truck': typeof FindTruckRoute
  '/icey-crew': typeof IceyCrewRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find-truck': typeof FindTruckRoute
  '/icey-crew': typeof IceyCrewRoute
  '/menu': typeof MenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find-truck': typeof FindTruckRoute
  '/icey-crew': typeof IceyCrewRoute
  '/menu': typeof MenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/find-truck'
    | '/icey-crew'
    | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community' | '/events' | '/find-truck' | '/icey-crew' | '/menu'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/events'
    | '/find-truck'
    | '/icey-crew'
    | '/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  FindTruckRoute: typeof FindTruckRoute
  IceyCrewRoute: typeof IceyCrewRoute
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icey-crew': {
      id: '/icey-crew'
      path: '/icey-crew'
      fullPath: '/icey-crew'
      preLoaderRoute: typeof IceyCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-truck': {
      id: '/find-truck'
      path: '/find-truck'
      fullPath: '/find-truck'
      preLoaderRoute: typeof FindTruckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  FindTruckRoute: FindTruckRoute,
  IceyCrewRoute: IceyCrewRoute,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
